[package]
name = "convert"
version = "0.1.0"
authors = ["Xanzis <xander@xanderh.me>"]
edition = "2018"

[dependencies.derive_more]
version = "0.99.0"
default-features = false
features = ["add", "mul"]